fraud:
  outputs:
    dev:
      account: df99339.sa-east-1.aws
      database: PROJECT
      password: H-Gt=APj~"vnxS2DM];,#N
      role: AIRBYTE_ROLE
      schema: silver
      threads: 1
      type: snowflake
      user: AIRBYTE_USER
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
